import { CANONICAL_ORIGIN, expect, test } from "./fixtures";

/** Files crawlers and feed readers fetch: generated by routes in `app/`, never from `public/`. */
const MACHINE_ROUTES: { path: string; contentType: RegExp; contains?: string }[] = [
  { path: "/sitemap.xml", contentType: /^application\/xml/, contains: `<loc>${CANONICAL_ORIGIN}/` },
  { path: "/robots.txt", contentType: /^text\/plain/, contains: `Sitemap: ${CANONICAL_ORIGIN}/sitemap.xml` },
  { path: "/feed.xml", contentType: /^application\/rss\+xml/, contains: "<rss" },
  { path: "/llms.txt", contentType: /^text\/(markdown|plain)/, contains: CANONICAL_ORIGIN },
  { path: "/opengraph-image", contentType: /^image\/png/ },
];

for (const { path, contentType, contains } of MACHINE_ROUTES) {
  test(`${path} answers 200 with the right content type`, async ({ request }) => {
    const response = await request.get(path);
    expect(response.status()).toBe(200);
    expect(response.headers()["content-type"]).toMatch(contentType);
    if (contains) expect(await response.text()).toContain(contains);
  });
}

test.describe("/api/views", () => {
  test("rejects a body without a slug", async ({ request }) => {
    const response = await request.post("/api/views", { data: {} });
    expect(response.status()).toBe(400);
  });

  test("does not count a slug that is not a post", async ({ request }) => {
    const response = await request.post("/api/views", { data: { slug: "no-such-post" } });
    expect(response.status()).toBe(404);
  });
});
