import type { Project } from "@/types/project";

const ME = "Thomas Moser";
const CRISTINA = "Cristina Andrés";

/** Ordered for display: featured first, then newest. */
export const projects: Project[] = [
  {
    slug: "la-minute-cine",
    title: "La Minute Ciné",
    summary:
      "French cinema website with reviews, festival coverage and interviews, edited through a Payload CMS back office.",
    context: "Built for a friend",
    stack: ["Next.js", "Payload CMS", "PostgreSQL", "Tailwind CSS", "Docker"],
    credits: { developedBy: [ME] },
    period: { start: "2026-04" },
    links: { live: "https://www.laminutecine.fr" },
    screenshot: "v2/la-minute-cine",
    video: "/videos/projects/la-minute-cine.mp4",
    featured: true,
  },
  {
    slug: "llm-trading-colosseum",
    title: "LLM Trading Colosseum",
    summary:
      "Research harness where several LLM-powered agents each manage a simulated €1,000 portfolio, to study their reasoning and biases. No real money involved.",
    stack: ["Python", "Anthropic API", "OpenAI API", "SQLModel", "Streamlit"],
    credits: { developedBy: [ME] },
    period: { start: "2026-05" },
    links: {},
  },
  {
    slug: "nous-deux",
    title: "Nous Deux",
    summary:
      "Privacy-first couple app with a shared calendar, period tracking and optional location sharing, plus its marketing website.",
    stack: ["Flutter", "Supabase", "Firebase", "Mapbox", "Next.js"],
    credits: { developedBy: [ME] },
    period: { start: "2026-02" },
    links: { live: "https://nous-deux-website.vercel.app", repo: "https://github.com/Eragon67360/nous-deux" },
    screenshot: "v2/nous-deux",
    video: "/videos/projects/nous-deux.mp4",
  },
  {
    slug: "le-bon-temperament",
    title: "Le Bon Tempérament",
    summary:
      "Digital ecosystem of a vocal and instrumental ensemble: public website with online payments, an admin dashboard and an Android app, in one monorepo.",
    stack: ["Next.js", "Turborepo", "Supabase", "Stripe", "HeroUI", "Cloudinary"],
    credits: { designedBy: [ME], developedBy: [ME] },
    period: { start: "2024-03", end: "2026-03" },
    links: {
      live: "https://www.lebontemperament.com",
      repo: "https://github.com/Eragon67360/lebontemperament_turbo",
    },
    screenshot: "v2/lebontemperament",
    video: "/videos/projects/le-bon-temperament.mp4",
  },
  {
    slug: "habit-forge",
    title: "HabitForge",
    summary: "Habit tracker to build good habits and break bad ones, with streaks and progress tracking.",
    stack: ["React Native", "Expo", "Next.js", "Turborepo", "Zustand"],
    credits: { developedBy: [ME] },
    period: { start: "2025-06" },
    links: { live: "https://habit-forge-web.vercel.app", repo: "https://github.com/Eragon67360/habit-forge" },
    screenshot: "v2/habit-forge",
    video: "/videos/projects/habit-forge.mp4",
  },
  {
    slug: "taylors-secret-garden",
    title: "Taylor's Secret Garden",
    summary: "Taylor Swift fan community with a forum, albums and tours.",
    stack: ["Next.js", "NextUI", "Clerk", "Supabase", "Deezer API"],
    credits: { developedBy: [ME] },
    period: { start: "2024-06" },
    links: {
      live: "https://taylorssecretgarden.vercel.app",
      repo: "https://github.com/Eragon67360/taylorssecretgarden",
    },
    screenshot: "v2/taylorssecretgarden",
    video: "/videos/projects/taylors-secret-garden.mp4",
  },
  {
    slug: "url-shortener",
    title: "URL Shortener",
    summary: "Link shortener with automatic cleanup of expired links by a daily scheduled job.",
    stack: ["Next.js", "PostgreSQL", "Vercel Cron"],
    credits: { designedBy: [ME], developedBy: [ME] },
    period: { start: "2024-06" },
    links: {
      live: "https://urlshortener.thomasmoserdev.com",
      repo: "https://github.com/Eragon67360/urlshortener",
    },
    screenshot: "v2/urlshortener",
    video: "/videos/projects/url-shortener.mp4",
  },
  {
    slug: "designer-portfolio",
    title: "Designer Portfolio",
    summary: `Portfolio website of UX/UI designer ${CRISTINA}.`,
    stack: ["Next.js", "Tailwind CSS"],
    credits: { designedBy: [CRISTINA], developedBy: [ME] },
    links: { live: "https://cristinadesigns.vercel.app" },
    screenshot: "v2/cristina-designs",
    video: "/videos/projects/designer-portfolio.mp4",
  },
  {
    slug: "curefab",
    title: "Curefab",
    summary: "Company website for Curefab Technologies in Munich, built on ConcreteCMS.",
    context: "Client project",
    stack: ["PHP", "ConcreteCMS", "SCSS"],
    credits: { designedBy: [CRISTINA], developedBy: [ME] },
    period: { start: "2023-10", end: "2024-02" },
    links: { live: "https://www.curefab.com" },
    screenshot: "v2/curefab",
    video: "/videos/projects/curefab.mp4",
  },
  {
    slug: "moca",
    title: "MOCA",
    summary: "Multilingual website of MOCA, with booking, subscriptions and online payments.",
    context: `My former micro-enterprise with designer ${CRISTINA}`,
    stack: ["Next.js", "Prisma", "Clerk", "Stripe", "next-intl"],
    credits: { developedBy: [ME] },
    period: { start: "2023-09", end: "2023-12" },
    links: { live: "https://moca-portfolio.vercel.app", repo: "https://github.com/Eragon67360/moca-portfolio" },
    screenshot: "v2/moca",
    video: "/videos/projects/moca.mp4",
  },
  {
    slug: "openai-clone",
    title: "OpenAI Clone",
    summary: "Cross-platform ChatGPT and DALL·E 2 client with more control over the model settings.",
    stack: ["Python", "Flet", "OpenAI API"],
    credits: { developedBy: [ME] },
    period: { start: "2023-01" },
    links: { repo: "https://github.com/Eragon67360/chatgpt_v2" },
    screenshot: "chatgptv2",
    video: "/videos/projects/openai-clone.mp4",
  },
  {
    slug: "stopviolence",
    title: "StopViolence",
    summary: "Android app to call trusted contacts or the emergency services quickly in a dangerous situation.",
    context: "School project, HE-Arc Neuchâtel",
    stack: ["Java", "Android"],
    credits: { designedBy: [CRISTINA], developedBy: [ME, "Ronan Riboulet"] },
    links: { repo: "https://github.com/Eragon67360/stop-violence" },
    screenshot: "stopviolence",
    video: "/videos/projects/stopviolence.mp4",
  },
  {
    slug: "musescore",
    title: "MuseScore",
    summary: "My sheet music arrangements, published on MuseScore.",
    stack: [],
    credits: { developedBy: [ME] },
    links: { live: "https://musescore.com/thomas_moser" },
    screenshot: "musescore",
  },
];
