import React from "react";
import Link from "next/link";
import Head from 'next/head';


export default function Home(){
  return (
    <div className="flex flex-col h-screen">
      <Head>
        <title>Thomas Moser Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        data-mdb-ripple="true"
        className=" p-5 text-center flex flex-col h-screen bg-hero bg-no-repeat bg-cover bg-center bg-fixed backdrop-filter brightness-100"        
      >
        <div className="mask m-auto">
          <div className="d-flex justify-content-center  align-items-center h-100 ">
            <div className="text-white brightness-100">
              <h1 className="mb-1 md:mb-3 text-2xl md:text-6xl lg:text-8xl py-5 md:py-10">Thomas Moser&apos;s Portfolio</h1>
              <h4 className="mb-1 md:mb-3 text-xl md:text-3xl lg:text-5xl py-1 md:py-4">Welcome to my portfolio</h4>
              
              <div className="py-5 flex justify-center items-center">
                <Link type="button"
                  href="/home"
                  passHref
                  className="px-6 md:text-md lg:text-xl py-2 border-2 mx-2 bg-white border-white text-black font-medium text-xs leading-tight uppercase rounded hover:bg-black hover:text-white hover:bg-opacity-5 focus:outline-none focus:ring-0 transition duration-150 ease-in-out"
                  data-mdb-ripple="true"
                  data-mdb-ripple-color="light">
                  Get started
                </Link>
                <a
                  className="borderinline-block" 
                  href="CV_Thomas_MOSER.pdf"
                  alt="alt text"
                  target="_blank"
                  rel="noopener noreferrer"
                  >
                  <button type="button"
                    className="border-2 text-xs md:text-md lg:text-xl inline-flex mx-2 py-2 px-6 bg-none border-white text-white font-medium uppercase rounded hover:bg-black hover:text-white hover:bg-opacity-5 focus:outline-none focus:ring-0 transition duration-150 ease-in-out"
                    data-mdb-ripple="true"
                    data-mdb-ripple-color="light">
                      <svg className="m-auto fill-current w-4 h-4 mr-2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M13 8V2H7v6H2l8 8 8-8h-5zM0 18h20v2H0v-2z"/></svg>
                      <span>Resume</span> 
                  </button>
                </a>

              </div>
              

            </div>
          </div>
        </div>
      </div>
    </div>
  )
}